server:  port: 8888spring:  datasource:    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    username: root
    password: DES@PtzGa+1Ea/o=